// front/src/app/components/detection_visualization/DetectionVisualizationPanel.tsx
"use client";

import { useMemo, useState } from "react";

import useDetectionTemporalData from "@/app/hooks/api/useDetectionTemporalData";
import PolarHeatmap from "./PolarHeatmap";

import Loading from "@/lib/components/ui/Loading";

// ============================================================================
// Types
// ============================================================================

interface DetectionVisualizationPanelProps {
  runUuid: string;
  filterApplicationUuid?: string;
  /** Maximum number of species to display in grid view */
  maxGridItems?: number;
}

// ============================================================================
// Main Component
// ============================================================================

export default function DetectionVisualizationPanel({
  runUuid,
  filterApplicationUuid,
  maxGridItems = 12,
}: DetectionVisualizationPanelProps) {
  const [showAll, setShowAll] = useState(false);

  // Fetch temporal data
  const { data, isLoading, isError, error } = useDetectionTemporalData({
    runUuid,
    filterApplicationUuid,
  });

  // Sort species by total detections
  const sortedSpecies = useMemo(() => {
    if (!data?.species) return [];
    return [...data.species].sort((a, b) => b.total_detections - a.total_detections);
  }, [data?.species]);

  // Limit displayed species unless showAll is true
  const displayedSpecies = useMemo(() => {
    if (showAll) return sortedSpecies;
    return sortedSpecies.slice(0, maxGridItems);
  }, [sortedSpecies, showAll, maxGridItems]);

  const hasMore = sortedSpecies.length > maxGridItems;

  // ============================================================================
  // Render States
  // ============================================================================

  if (isLoading) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Loading />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="flex min-h-[200px] flex-col items-center justify-center gap-2 text-center">
        <div className="text-red-500">
          <svg
            className="mx-auto h-10 w-10"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
            />
          </svg>
        </div>
        <p className="text-sm text-stone-600 dark:text-stone-400">
          Failed to load detection data
        </p>
        <p className="text-xs text-stone-400">
          {error instanceof Error ? error.message : "Unknown error"}
        </p>
      </div>
    );
  }

  if (!data || sortedSpecies.length === 0) {
    return (
      <div className="flex min-h-[200px] flex-col items-center justify-center gap-2 text-center">
        <div className="text-stone-400">
          <svg
            className="mx-auto h-10 w-10"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"
            />
          </svg>
        </div>
        <p className="text-sm text-stone-600 dark:text-stone-400">
          No detections found
        </p>
        <p className="text-xs text-stone-400">
          Run a foundation model to generate detection data.
        </p>
      </div>
    );
  }

  // ============================================================================
  // Main Render
  // ============================================================================

  const totalDetections = sortedSpecies.reduce((sum, s) => sum + s.total_detections, 0);

  return (
    <div className="space-y-4">
      {/* Header with Stats */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-6">
          <div>
            <div className="text-2xl font-semibold text-stone-900 dark:text-stone-100">
              {sortedSpecies.length}
            </div>
            <div className="text-xs text-stone-500">Species</div>
          </div>
          <div>
            <div className="text-2xl font-semibold text-stone-900 dark:text-stone-100">
              {totalDetections.toLocaleString()}
            </div>
            <div className="text-xs text-stone-500">Detections</div>
          </div>
          {data.date_range && (
            <div>
              <div className="text-sm font-medium text-stone-700 dark:text-stone-300">
                {new Date(data.date_range[0]).toLocaleDateString("ja-JP")} - {new Date(data.date_range[1]).toLocaleDateString("ja-JP")}
              </div>
              <div className="text-xs text-stone-500">Date range</div>
            </div>
          )}
        </div>
      </div>

      {/* Polar Heatmap Grid */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {displayedSpecies.map((species) => (
          <div
            key={species.scientific_name}
            className="rounded-xl border border-stone-200 bg-white p-4 dark:border-stone-700 dark:bg-stone-900"
          >
            <PolarHeatmap
              data={species.detections}
              scientificName={species.scientific_name}
              commonName={species.common_name ?? undefined}
              totalDetections={species.total_detections}
              size={200}
            />
          </div>
        ))}
      </div>

      {/* Show More / Show Less Button */}
      {hasMore && (
        <div className="flex justify-center">
          <button
            type="button"
            onClick={() => setShowAll(!showAll)}
            className="rounded-lg border border-stone-200 bg-white px-4 py-2 text-sm font-medium text-stone-700 hover:bg-stone-50 dark:border-stone-700 dark:bg-stone-800 dark:text-stone-300 dark:hover:bg-stone-700"
          >
            {showAll
              ? "Show less"
              : `Show all ${sortedSpecies.length} species`}
          </button>
        </div>
      )}
    </div>
  );
}

// apps/web/src/lib/components/detection/DetectionVisualizationPanel.svelte
<script lang="ts">
  /**
   * DetectionVisualizationPanel - Grid of PolarHeatmap charts for multiple species.
   *
   * Displays up to 12 species by default with a toggle to show all.
   */

  import type { SpeciesTemporalData } from '$lib/types/detection';
  import PolarHeatmap from './PolarHeatmap.svelte';
  import * as m from '$lib/paraglide/messages';

  export let species: SpeciesTemporalData[];

  const DEFAULT_VISIBLE = 12;

  let showAll = false;

  $: visibleSpecies = showAll ? species : species.slice(0, DEFAULT_VISIBLE);
  $: hasMore = species.length > DEFAULT_VISIBLE;
  $: hiddenCount = species.length - DEFAULT_VISIBLE;
</script>

<div class="space-y-6">
  {#if species.length === 0}
    <div class="rounded-lg border border-stone-200 bg-stone-50 px-4 py-12 text-center">
      <svg
        class="mx-auto h-10 w-10 text-stone-300"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
        aria-hidden="true"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="1.5"
          d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
        />
      </svg>
      <p class="mt-3 text-sm font-medium text-stone-700">{m.detection_viz_no_activity_title()}</p>
      <p class="mt-1 text-xs text-stone-500">
        {m.detection_viz_no_activity_body()}
      </p>
    </div>
  {:else}
    <!-- Species count -->
    <p class="text-sm text-stone-500">
      {#if !showAll && hasMore}
        {m.detection_viz_showing_top({ top: DEFAULT_VISIBLE, total: species.length })}
      {:else}
        {m.detection_viz_species_detected({ count: species.length })}
      {/if}
    </p>

    <!-- Responsive grid -->
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      {#each visibleSpecies as sp (sp.tag_id)}
        <div class="rounded-lg border border-stone-200 bg-white p-4 shadow-sm">
          <PolarHeatmap
            data={sp.detections}
            scientificName={sp.scientific_name}
            commonName={sp.common_name}
            totalDetections={sp.total_detections}
            size={220}
          />
        </div>
      {/each}
    </div>

    <!-- Show all / collapse toggle -->
    {#if hasMore}
      <div class="flex justify-center">
        <button
          type="button"
          on:click={() => (showAll = !showAll)}
          class="inline-flex items-center gap-1.5 rounded-md border border-stone-300 bg-white px-4 py-2 text-sm font-medium text-stone-600 hover:bg-stone-50 focus:outline-none focus:ring-2 focus:ring-emerald-400 transition-colors"
        >
          {#if showAll}
            <svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd" />
            </svg>
            {m.detection_viz_show_fewer()}
          {:else}
            <svg class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
            {m.detection_viz_show_all({ count: species.length })}
          {/if}
        </button>
      </div>
    {/if}
  {/if}
</div>
