// front/src/lib/components/ui/Button.tsx
import classNames from "classnames";
import { ForwardedRef, forwardRef } from "react";
import type { ButtonHTMLAttributes, ReactNode } from "react";

import type { Mode, Variant } from "@/lib/components/common";

const FOCUS_STYLE = "focus:ring-4 focus:ring-emerald-500/50 focus:outline-none";

const CLASS_NAMES = {
  filled: {
    primary:
      "border-emerald-500 bg-emerald-300 hover:bg-emerald-500 dark:bg-emerald-600 dark:hover:bg-emerald-700 dark:ring-offset-opacity-50 disabled:bg-emerald-300 dark:disabled:bg-emerald-700",
    secondary:
      "border-stone-300 dark:border-stone-600 bg-stone-100 hover:bg-stone-200 dark:bg-stone-700 dark:hover:bg-stone-800 disabled:bg-stone-300 dark:disabled:bg-stone-700 dark:text-stone-400",
    danger:
      "border-rose-500 bg-rose-700 hover:bg-rose-800 dark:bg-rose-600 dark:hover:bg-rose-700 disabled:bg-rose-300 dark:disabled:bg-rose-700",
    success:
      "border-green-500 bg-green-700 hover:bg-green-800 dark:bg-green-600 dark:hover:bg-green-700 disabled:bg-green-300 dark:disabled:bg-green-700",
    warning:
      "border-yellow-500 bg-yellow-700 hover:bg-yellow-800 dark:bg-yellow-600 dark:hover:bg-yellow-700 disabled:bg-yellow-300 dark:disabled:bg-yellow-700",
    info: "border-blue-500 bg-blue-700 hover:bg-blue-800 dark:bg-blue-600 dark:hover:bg-blue-700 disabled:bg-blue-300 dark:disabled:bg-blue-700",
    common:
      "border text-stone-900 dark:text-stone-100 disabled:text-stone-500 dark:disabled:text-stone-300",
  },
  outline: {
    primary:
      "border-emerald-500 hover:bg-emerald-300 dark:hover:bg-emerald-700",
    secondary: "border-stone-500 hover:bg-stone-300 dark:hover:bg-stone-700",
    danger: "border-rose-500 hover:bg-rose-300 dark:hover:bg-rose-700",
    success: "border-green-500 hover:bg-green-300 dark:hover:bg-green-700",
    warning: "border-yellow-500 hover:bg-yellow-300 dark:hover:bg-yellow-700",
    info: "border-blue-500 hover:bg-blue-300 dark:hover:bg-blue-700",
    common: "border bg-transparent text-stone-900 dark:text-stone-100",
  },
  text: {
    primary:
      "text-emerald-500 stroke-emerald-500 hover:stroke-emerald-300 dark:hover:stroke-emerald-800",
    secondary:
      "text-stone-500 stroke-stone-500 hover:stroke-stone-800 dark:hover:stroke-stone-300 disabled:stroke-stone-500 dark:disabled:stroke-stone-500",
    danger:
      "text-rose-500 stroke-rose-500 hover:stroke-rose-300 dark:hover:stroke-rose-800",
    success:
      "text-green-500 stroke-green-500 hover:stroke-green-300 dark:hover:stroke-green-800",
    warning:
      "text-yellow-500 stroke-yellow-500 hover:stroke-yellow-300 dark:hover:stroke-yellow-800",
    info: "text-blue-500 stroke-blue-500 hover:stroke-blue-300 dark:hover:stroke-blue-800",
    common:
      "bg-transparent hover:underline hover:decoration-solid hover:decoration-2 hover:underline-offset-2 disabled:no-underline disabled:font-medium stroke-2 hover:stroke-4 disabled:stroke-1",
  },
};

export function getButtonClassName({
  variant = "primary",
  mode = "filled",
  padding = "p-2.5",
  align = "text-center",
}: {
  variant?: Variant;
  mode?: Mode;
  padding?: string;
  align?: "text-center" | "text-left" | "text-right";
}) {
  // Ensure mode is valid, fallback to "filled" if not
  const validMode: Mode = CLASS_NAMES[mode] ? mode : "filled";

  return classNames(
    CLASS_NAMES[validMode][variant],
    CLASS_NAMES[validMode]["common"],
    FOCUS_STYLE,
    padding,
    align,
    "group flex flex-row items-center rounded-lg text-sm font-medium",
  );
}

const Button = forwardRef(function Button(
  {
    children,
    variant = "primary",
    mode = "filled",
    padding = "p-2.5",
    align = "text-center",
    className,
    ...props
  }: {
    children: ReactNode;
    variant?: Variant;
    padding?: string;
    align?: "text-center" | "text-left" | "text-right";
    mode?: Mode;
  } & Omit<ButtonHTMLAttributes<HTMLButtonElement>, "ref">,
  ref: ForwardedRef<HTMLButtonElement>,
) {
  const baseClass = getButtonClassName({ variant, mode, padding, align });
  return (
    <button className={classNames(baseClass, className)} {...props} ref={ref}>
      {children}
    </button>
  );
});

export default Button;

// apps/web/src/lib/components/Button.svelte
<script lang="ts">
  /**
   * Reusable button component
   */
  interface Props {
    variant?: 'primary' | 'secondary' | 'outline' | 'ghost';
    size?: 'sm' | 'md' | 'lg';
    disabled?: boolean;
    type?: 'button' | 'submit' | 'reset';
    onclick?: () => void;
    children?: import('svelte').Snippet;
  }

  let {
    variant = 'primary',
    size = 'md',
    disabled = false,
    type = 'button',
    onclick,
    children,
  }: Props = $props();

  const variantClasses = {
    primary:
      'bg-primary-600 text-white hover:bg-primary-700 focus:ring-primary-500 dark:bg-primary-500 dark:text-stone-50 dark:hover:bg-primary-400',
    secondary: 'bg-secondary-600 text-white hover:bg-secondary-700 focus:ring-secondary-500',
    outline:
      'border-2 border-primary-600 text-primary-600 hover:bg-primary-50 focus:ring-primary-500',
    ghost: 'text-primary-600 hover:bg-primary-50 focus:ring-primary-500',
  };

  const sizeClasses = {
    sm: 'px-3 py-1.5 text-sm',
    md: 'px-4 py-2 text-base',
    lg: 'px-6 py-3 text-lg',
  };

  const baseClasses =
    'inline-flex items-center justify-center font-medium rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:cursor-not-allowed';

  const classes = $derived(`${baseClasses} ${variantClasses[variant]} ${sizeClasses[size]}`);
</script>

<button {type} {disabled} class={classes} {onclick}>
  {@render children?.()}
</button>
