// front/src/lib/components/metadata/SiteForm.tsx
"use client";

import { useCallback, useState } from "react";
import dynamic from "next/dynamic";
import { MapPin } from "lucide-react";

import { Group, Input } from "@/lib/components/inputs";
import Button from "@/lib/components/ui/Button";
import Spinner from "@/lib/components/ui/Spinner";

import type { Site, SiteCreate, SiteUpdate } from "@/lib/types";

const H3HexPicker = dynamic(() => import("@/lib/components/maps/H3HexPicker"), {
  ssr: false,
  loading: () => (
    <div className="flex h-[400px] items-center justify-center rounded-lg border border-stone-200 bg-white dark:border-stone-700 dark:bg-stone-900">
      <Spinner />
    </div>
  ),
});

interface SiteFormProps {
  site?: Site;
  projectId: string;
  onSubmit: (data: SiteCreate | SiteUpdate) => void | Promise<void>;
  onCancel: () => void;
  isSubmitting?: boolean;
}

export default function SiteForm({
  site,
  projectId,
  onSubmit,
  onCancel,
  isSubmitting = false,
}: SiteFormProps) {
  const isEditing = Boolean(site);

  const [siteId, setSiteId] = useState(site?.site_id ?? "");
  const [siteName, setSiteName] = useState(site?.site_name ?? "");
  const [h3Index, setH3Index] = useState(site?.h3_index ?? "");

  const [resolution, setResolution] = useState(7);

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();

      if (site) {
        const updateData: SiteUpdate = {};
        if (siteName !== site.site_name) updateData.site_name = siteName;
        if (h3Index !== site.h3_index) updateData.h3_index = h3Index;

        await onSubmit(updateData);
      } else {
        const createData: SiteCreate = {
          site_id: siteId,
          site_name: siteName,
          project_id: projectId,
          h3_index: h3Index,
          images: [],
        };
        await onSubmit(createData);
      }
    },
    [isEditing, site, siteId, siteName, projectId, h3Index, onSubmit],
  );

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {!isEditing && (
        <Group label="Site ID" name="site_id" help="Unique identifier for this site">
          <Input
            value={siteId}
            onChange={(e) => setSiteId(e.target.value)}
            placeholder="e.g., SITE001"
            required
          />
        </Group>
      )}

      <Group label="Site Name" name="site_name">
        <Input
          value={siteName}
          onChange={(e) => setSiteName(e.target.value)}
          placeholder="e.g., Forest Clearing North"
          required
        />
      </Group>

      <Group
        label="Location (H3 Index)"
        name="h3_index"
        help="Click on the map to select a location. The H3 index provides privacy by using hexagonal grids."
      >
        <div className="space-y-2">
          <Input
            value={h3Index}
            onChange={(e) => setH3Index(e.target.value)}
            placeholder="Click on map or paste H3 index"
            required
          />
          <H3HexPicker
            value={h3Index}
            onChange={setH3Index}
            resolution={resolution}
            onResolutionChange={setResolution}
          />
        </div>
      </Group>

      <div className="flex justify-end gap-2 pt-4 border-t border-stone-200 dark:border-stone-700">
        <Button
          type="button"
          variant="secondary"
          onClick={onCancel}
          disabled={isSubmitting}
        >
          Cancel
        </Button>
        <Button
          type="submit"
          variant="primary"
          disabled={isSubmitting || !siteId || !siteName || !h3Index}
        >
          {isSubmitting ? (
            <>
              <Spinner className="w-4 h-4 mr-2" />
              {isEditing ? "Updating..." : "Creating..."}
            </>
          ) : (
            <>
              <MapPin className="w-4 h-4 mr-2" />
              {isEditing ? "Update Site" : "Create Site"}
            </>
          )}
        </Button>
      </div>
    </form>
  );
}

// apps/web/src/lib/components/data/SiteForm.svelte
<script lang="ts">
  import type { Site, SiteCreate } from '$lib/types/data';
  import H3MapPicker from '$lib/components/map/H3MapPicker.svelte';

  export let site: Site | null = null;
  export let onSubmit: (data: SiteCreate) => Promise<void>;
  export let onCancel: () => void = () => {};

  let name = site?.name ?? '';
  let h3Index = site?.h3_index ?? '';
  let resolution = 9;
  let isSubmitting = false;
  let error = '';

  function handleMapSelect(index: string, center: [number, number]) {
    h3Index = index;
  }

  async function handleSubmit() {
    if (!name.trim()) {
      error = 'Name is required';
      return;
    }
    if (!h3Index) {
      error = 'Please select a location on the map';
      return;
    }

    error = '';
    isSubmitting = true;

    try {
      await onSubmit({ name: name.trim(), h3_index: h3Index });
    } catch (e) {
      error = e instanceof Error ? e.message : 'Failed to save site';
    } finally {
      isSubmitting = false;
    }
  }
</script>

<form class="site-form" on:submit|preventDefault={handleSubmit}>
  <div class="form-group">
    <label for="name">Site Name *</label>
    <input
      type="text"
      id="name"
      bind:value={name}
      placeholder="Enter site name"
      maxlength="200"
      required
    />
  </div>

  <div class="form-group">
    <label>Location *</label>
    <p class="help-text">Click on the map to select an H3 hexagon for this site.</p>
    <H3MapPicker h3Index={h3Index} {resolution} onSelect={handleMapSelect} />
  </div>

  {#if h3Index}
    <div class="form-group">
      <label>Selected H3 Index</label>
      <input type="text" value={h3Index} readonly class="readonly" />
    </div>
  {/if}

  {#if error}
    <div class="error-message">{error}</div>
  {/if}

  <div class="form-actions">
    <button type="button" class="btn-secondary" on:click={onCancel} disabled={isSubmitting}>
      Cancel
    </button>
    <button type="submit" class="btn-primary" disabled={isSubmitting || !name || !h3Index}>
      {#if isSubmitting}
        Saving...
      {:else}
        {site ? 'Update Site' : 'Create Site'}
      {/if}
    </button>
  </div>
</form>

<style>
  .site-form {
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  .form-group label {
    font-weight: 500;
    font-size: 0.875rem;
    color: #374151;
  }

  .help-text {
    font-size: 0.75rem;
    color: #6b7280;
    margin: 0;
  }

  input[type='text'] {
    padding: 0.625rem 0.75rem;
    border: 1px solid #d1d5db;
    border-radius: 0.375rem;
    font-size: 0.875rem;
    transition: border-color 0.15s ease;
  }

  input[type='text']:focus {
    outline: none;
    border-color: #3b82f6;
    box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
  }

  input.readonly {
    background: #f9fafb;
    color: #6b7280;
    font-family: monospace;
  }

  .error-message {
    padding: 0.75rem;
    background: #fef2f2;
    border: 1px solid #fecaca;
    border-radius: 0.375rem;
    color: #dc2626;
    font-size: 0.875rem;
  }

  .form-actions {
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
    padding-top: 1rem;
    border-top: 1px solid #e5e7eb;
  }

  .btn-primary,
  .btn-secondary {
    padding: 0.625rem 1.25rem;
    font-size: 0.875rem;
    font-weight: 500;
    border-radius: 0.375rem;
    cursor: pointer;
    transition: all 0.15s ease;
  }

  .btn-primary {
    background: #3b82f6;
    color: white;
    border: none;
  }

  .btn-primary:hover:not(:disabled) {
    background: #2563eb;
  }

  .btn-primary:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .btn-secondary {
    background: white;
    color: #374151;
    border: 1px solid #d1d5db;
  }

  .btn-secondary:hover:not(:disabled) {
    background: #f9fafb;
  }
</style>
